### ISSUE TITLE
Auth Setup

### ISSUE THREAD

**Issue by pconde705** [pconde705/wellspring#1]
Have completed initial setup of Auth, but still requires a demo user button.

**Comment by dallashall** [comment]
It looks great so far. Just a few things before I approve it:

- [x] Make sure to preventDefault() on your demo login (it is triggering a re-render)
- [x] Get the demo login working

**Comment by pconde705** [comment]
Got it to work, will add animation later.

**Comment by pconde705** [comment]
Forgot to add it under milestone
