### ISSUE TITLE
Backer Rewards

### ISSUE THREAD

**Issue by pconde705** [pconde705/wellspring#4]
You can click on the button to add money, and on the backer rewards them selves but they won't update unless you refresh the page.

**Comment by pconde705** [comment]
There's some fine tuning that needs to be done, for instance the percentage doesn't update, and page has to refresh before we can see the results.

**Comment by dallashall** [comment]
On the home page, the nav bar shows total projects and dollars backed. That should reflect the state of the app and not be hard coded (or at least be hard-coded closer to what it is).

**Comment by dallashall** [comment]
No lorem ipsom text.

**Comment by dallashall** [comment]
Every project should have at least one reward.

**Comment by dallashall** [comment]
All buttons on the page should have cursor: pointer CSS styling.
